{
  "comments": [
    {
      "key": {
        "uuid": "1a486d77_0a65c9e0",
        "filename": "tools/pkt_gen/testcenter/testcenter-rfc2544-rest.py",
        "patchSetId": 4
      },
      "lineNbr": 37,
      "author": {
        "id": 2851
      },
      "writtenOn": "2016-03-10T15:51:48Z",
      "side": 1,
      "message": "Since this is raising an exception should we log it as an error or exception level instead of debug? Just a thought.",
      "revId": "e53bc3407e4670e6eb16b741bfc563fab3a912ca",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "1a486d77_ca5e9112",
        "filename": "tools/pkt_gen/testcenter/testcenter-rfc2544-rest.py",
        "patchSetId": 4
      },
      "lineNbr": 322,
      "author": {
        "id": 2851
      },
      "writtenOn": "2016-03-10T15:51:48Z",
      "side": 1,
      "message": "Looks like you missed a print to log message here :).",
      "revId": "e53bc3407e4670e6eb16b741bfc563fab3a912ca",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "1a486d77_aa9b55c8",
        "filename": "tools/pkt_gen/testcenter/testcenter-rfc2544-rest.py",
        "patchSetId": 4
      },
      "lineNbr": 327,
      "author": {
        "id": 2851
      },
      "writtenOn": "2016-03-10T15:51:48Z",
      "side": 1,
      "message": "print to log message",
      "revId": "e53bc3407e4670e6eb16b741bfc563fab3a912ca",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "1a486d77_8aa099f5",
        "filename": "tools/pkt_gen/testcenter/testcenter-rfc2544-rest.py",
        "patchSetId": 4
      },
      "lineNbr": 330,
      "author": {
        "id": 2851
      },
      "writtenOn": "2016-03-10T15:51:48Z",
      "side": 1,
      "message": "print to log message",
      "revId": "e53bc3407e4670e6eb16b741bfc563fab3a912ca",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "1a486d77_6aa55d03",
        "filename": "tools/pkt_gen/testcenter/testcenter-rfc2544-rest.py",
        "patchSetId": 4
      },
      "lineNbr": 336,
      "author": {
        "id": 2851
      },
      "writtenOn": "2016-03-10T15:51:48Z",
      "side": 1,
      "message": "print to log message",
      "revId": "e53bc3407e4670e6eb16b741bfc563fab3a912ca",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "1a486d77_4aaaa1d5",
        "filename": "tools/pkt_gen/testcenter/testcenter-rfc2544-rest.py",
        "patchSetId": 4
      },
      "lineNbr": 388,
      "author": {
        "id": 2851
      },
      "writtenOn": "2016-03-10T15:51:48Z",
      "side": 1,
      "message": "print to log message",
      "revId": "e53bc3407e4670e6eb16b741bfc563fab3a912ca",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "1a486d77_ea614dd4",
        "filename": "tools/pkt_gen/testcenter/testcenter-rfc2544-rest.py",
        "patchSetId": 4
      },
      "lineNbr": 558,
      "author": {
        "id": 2851
      },
      "writtenOn": "2016-03-10T15:51:48Z",
      "side": 1,
      "message": "Again here for error level versus debug. Errors are easier to find that DEBUG messages. There are a lot of debug messages seen when running VSPerf.",
      "revId": "e53bc3407e4670e6eb16b741bfc563fab3a912ca",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    }
  ]
}